### ISSUE TITLE
Use outside Terraform?

### ISSUE THREAD

**Issue by alexpdp7** [mrparkers/terraform-provider-keycloak#766] opened 2022-11-09 09:37 UTC
This Terraform module seems to contain the most advanced configuration-as-code engine for Keycloak. It looks better superficially than what I believe was the state-of-the-art, https://github.com/adorsys/keycloak-config-cli .

I am not a Terraform user, but I am interested in maintaining Keycloak configuration as code. I assume I could hack something to run Terraform as part of the rest of my infra as code setup to manage Keycloak, but I think it would be nice if the core of the module was isolated, so it could be used outside Terraform. This way, it may be simple to produce adapters for other infra-as-code products.

Would someone consider doing this? I suspect the code might already support this, and it would probably simplify testing and improve maintainability anyway?

**Comment by mrparkers** [comment] 2022-12-05 03:48
Hi @alexpdp7, thanks for opening this issue.  The `keycloak` package of this provider was designed so it could be used independently of this provider.  So you can feel free to import that package within your own Go code and use it in the same way that the `provider` package does.

However, the versioning scheme for this project is only for the `provider` package - meaning that the `keycloak` package may experience some breaking changes between non-major releases.

If you would genuinely benefit from the `keycloak` package being moved to its own repository with its own release schedule, I could theoretically do that.  You might also be interested in using the [Terraform CDK](https://github.com/hashicorp/terraform-cdk) or [Pulumi](https://www.pulumi.com/registry/packages/keycloak/api-docs/), which uses this provider for its Keycloak integration.

I'm going to close this since I don't think there's anything actionable I can do, but feel free to re-open this if you have additional questions.

**Closed by mrparkers** 2022-12-05 03:48 UTC
