### ISSUE TITLE
[group] changing the parent of a group triggers a destruction/recreation: why not just an update ?

### ISSUE THREAD

**Issue by semangard** [mrparkers/terraform-provider-keycloak#431] opened 2020-11-04 22:32 UTC
Hello,

I changed the parent of a group and it triggered a destruction+ recreation; why does it not trigger only an update ?

(If I rename a top group then all its subgroups are then also destroyed and recreated.... which is not always possible in real life)

**Comment by mrparkers** [comment] 2020-11-05 15:57
> I changed the parent of a group and it triggered a destruction+ recreation; why does it not trigger only an update?

To my knowledge, there is no Keycloak API that allows you to move one group from one parent to another.  So this isn't an updatable field - the only way to change a group's parent is to delete it and recreate it with the correct parent.  This also doesn't seem to be possible in the GUI either.

This behavior can be changed if you know of a way to update a group's parent using the Keycloak API.

> If I rename a top group then all its subgroups are then also destroyed and recreated

I just tested this against v2.0.0 and this doesn't seem to be the case.  I'm able to rename a parent group just fine, without child groups being destroyed and recreated.

If you're sure that this is an issue, can you provide me with some sample HCL and some steps to reproduce this?

**Comment by semangard** [comment] 2020-11-05 20:55
Thanks for your feedback; here is my example

1) Here is the initial hierarchy ::
![image](https://user-images.githubusercontent.com/57065741/98294978-15c77e00-1fb1-11eb-9445-9cccf1491f6f.png)

with the initial TF code ::

![image](https://user-images.githubusercontent.com/57065741/98295019-2841b780-1fb1-11eb-9521-0d89e67c1dfd.png)

2) Then I make this change
![image](https://user-images.githubusercontent.com/57065741/98295066-3b548780-1fb1-11eb-9d36-4f746291d70b.png)

it triggers recreations ::
![image](https://user-images.githubusercontent.com/57065741/98295102-4dcec100-1fb1-11eb-901f-dc03e5f234ce.png)

for example ::

![image](https://user-images.githubusercontent.com/57065741/98295141-62ab5480-1fb1-11eb-83ba-94837cc2b0d2.png)

another example (the roles linked to the groups)

![image](https://user-images.githubusercontent.com/57065741/98295181-72c33400-1fb1-11eb-97a6-029f533b1395.png)

and here is the result ::

![image](https://user-images.githubusercontent.com/57065741/98295285-a1d9a580-1fb1-11eb-8cca-0f7f8c3da1d2.png)

**Comment by mrparkers** [comment] 2020-11-05 21:00
Right, so what you're doing is changing the parent of one or more group.  To my knowledge, it isn't possible to update a group's parent in Keycloak, via the GUI or the API.  So the `parent_id` attribute is marked as `ForceNew` since the only way to change that is by deleting it and recreating it.

If you were to update the `name` attribute of a group (regardless of whether it is a parent or a child), that would happen without destroying the resource, since that is an updatable field.

**Comment by semangard** [comment] 2020-11-05 21:02
Sorry I removed my comments because you were right ;-)
I think I mixed up the two cases: moving vs renaming as far as I tried both nearly at the same period

**Comment by semangard** [comment] 2020-11-05 21:05
By the way I know indeed that moving is not possible in the UI.
But wouldn't it be possible with the admin API (update operation on groups) : update the subgroups attribute of the new and old  top group  ?

**Comment by mrparkers** [comment] 2020-11-05 21:23
Yeah, the `subGroups` field is returned via `GET /{realm}/groups`, but is ignored via `POST /{realm}/groups` (creating a child is done via `POST /{realm}/groups/{id}/children`), and is also ignored via `PUT /{realm}/groups/{id}` (the API docs call out that subGroups are ignored here).  So it doesn't appear to be updatable.

**Comment by semangard** [comment] 2020-11-05 21:25
OK, what a shame, it could have been useful...
Thanks

**Comment by mrparkers** [comment] 2020-11-05 21:44
Sorry about that 😅  but perhaps the Keycloak team would be receptive to this change if you open a ticket on their issue tracker: https://issues.redhat.com/projects/KEYCLOAK/issues.  They have been receptive to issues that I've opened here in the past.

**Closed by mrparkers** 2020-11-05 21:44 UTC

**Comment by semangard** [comment] 2020-11-05 21:50
OK that's in the box : https://issues.redhat.com/browse/KEYCLOAK-16192
